last_change = 2025-10-25T11:30:08.191884Z
addr = 0x192f0
size = 0x33e1
name = "m0lewarden::main"

[header]
last_change = 2025-10-25T03:41:43.362801Z
name = "m0lewarden::main"
addr = 0x192f0

[header.args]

[stack_vars.-0x10]
last_change = 2025-10-25T03:41:12.031886Z
offset = -16
name = "some_buf"
type = "DisplayArgPair"
size = 0x4030
addr = 0x192f0

[stack_vars.-0x4030]
offset = -16432
name = "temp_formatted_out"
type = "__int128"
size = 0x10
addr = 0x192f0

[stack_vars.-0x40e0]
offset = -16608
name = "_expected_word_count"
size = 0x8
addr = 0x192f0

[stack_vars.-0x40f8]
offset = -16632
name = "_input_word_count"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4268]
offset = -17000
name = "input_words"
type = "rust_str *"
size = 0x8
addr = 0x192f0

[stack_vars.-0x41d0]
offset = -16848
name = "total_word_arr_len"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4110]
offset = -16656
name = "total_word_len"
size = 0x8
addr = 0x192f0

[stack_vars.-0x3fe8]
offset = -16360
type = "long long"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4018]
offset = -16408
name = "temp_string"
type = "char *"
size = 0x30
addr = 0x192f0

[stack_vars.-0x4120]
offset = -16672
name = "file_content_vector"
type = "struct vector_string"
size = 0x18
addr = 0x192f0

[stack_vars.-0x4160]
offset = -16736
name = "some_len_len2"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4200]
offset = -16896
name = "__file_contents"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4158]
offset = -16728
name = "word_from_file"
size = 0x10
addr = 0x192f0

[stack_vars.-0x4078]
offset = -16504
name = "formatted_out"
size = 0x18
addr = 0x192f0

[stack_vars.-0x4060]
offset = -16480
type = "unsigned long long[3]"
size = 0x18
addr = 0x192f0

[stack_vars.-0x41f8]
offset = -16888
name = "_formatted_out"
size = 0x18
addr = 0x192f0

[stack_vars.-0x40f0]
offset = -16624
name = "input_vector_strings"
type = "vector_string"
size = 0x18
addr = 0x192f0

[stack_vars.-0x4108]
offset = -16648
name = "admin_phrase_vector"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4290]
offset = -17040
name = "end_of_input_strings"
type = "rust_str *"
size = 0x8
addr = 0x192f0

[stack_vars.-0x41d8]
offset = -16856
name = "input_strings"
size = 0x8
addr = 0x192f0

[stack_vars.-0x40b8]
offset = -16568
name = "__input_strings"
size = 0x8
addr = 0x192f0

[stack_vars.-0x42a0]
offset = -17056
name = "iterator"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4080]
offset = -16512
name = "seed"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4088]
offset = -16520
name = "wordlist_words_arr1_end"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4240]
offset = -16960
name = "new_word_length"
size = 0x8
addr = 0x192f0

[stack_vars.-0x41a0]
offset = -16800
name = "__new_word_storage"
size = 0x8
addr = 0x192f0

[stack_vars.-0x41c8]
offset = -16840
name = "number_string_from_word"
type = "char[20]"
size = 0x14
addr = 0x192f0

[stack_vars.-0x41a8]
offset = -16808
name = "number_string_we_got"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4270]
offset = -17008
name = "word_buff"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4090]
offset = -16528
name = "worlist_end"
size = 0x8
addr = 0x192f0

[stack_vars.-0x4100]
offset = -16640
type = "string_like **"
size = 0x8
addr = 0x192f0
