last_change = 2025-10-25T03:43:05.958111Z
name = "$FF49D1C98CE644E68ED0F9ED93C79411"
size = 0x18

[members.0x0]
name = "ptr"
offset = 0x0
type = "char *"
size = 0x8

[members.0x8]
name = "len"
offset = 0x8
type = "size_t"
size = 0x8

[members.0x10]
name = "cap"
offset = 0x10
type = "size_t"
size = 0x8
