last_change = 2025-10-25T06:31:44.835956Z
name = "file_content_arr"
size = 0x30

[members.0x0]
name = "data1"
offset = 0x0
type = "rust_str"
size = 0x10

[members.0x10]
name = "data2"
offset = 0x10
type = "rust_str"
size = 0x10

[members.0x20]
name = "data3"
offset = 0x20
type = "rust_str"
size = 0x10
