last_change = 2025-10-25T02:37:27.209279Z
name = "rust_str"
size = 0x10

[members.0x0]
name = "str"
offset = 0x0
type = "char *"
size = 0x8

[members.0x8]
name = "len"
offset = 0x8
type = "int"
size = 0x4
